# Generated by Django 4.2.7 on 2023-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('nebulosa', 'Nebulosa'), ('galaxia', 'Galaxia'), ('estrela', 'Estrela'), ('planeta', 'Planeta')], default='', max_length=150),
        ),
    ]
